name: confirmation sample
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: confirmation sample
        required: true
        type: boolean

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
      if: ${{ ! inputs.confirmation }}
    - run: echo 'finished'
